proj/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

proj/polls/urls.py
from django.urls import path
from polls.views import *
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('conkurs/<int:conkurs_id>/', views.conkurs, name='conkurs'),
    path('doc/<int:doc_id>/', views.doc, name='doc'),
    path('doc_z/<int:doc_id>/', views.doc_z, name='doc_z'),
    path('list_zay/', views.list_zay, name='list_zay'),######################
    path('results/<int:results_id>/', views.results, name='results'),
    # #ДОБАВЛЕНИЕ НОВЫХ ОБЪЕКТОВ
    # #Конкурс
    path('new_conkurs/', views.new_conkurs, name='new_conkurs'),
    # # Организация
    path('new_org/', views.new_org, name='new_org'),
    # #Заявка
    path('new_zay/', views.new_zay, name='new_zay'),
    
    
    # #РЕДАКТИРОВАНИЕ ОБЪЕКТОВ
    path('edit_conkurs/<int:conkurs_id>/', views.edit_conkurs, name='edit_conkurs'),
]

proj/polls/models.py
#-*- coding: utf-8 -*-
from django.core.files.storage import FileSystemStorage
from django.conf import settings

from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.
private_storage = FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT)
media_storage = FileSystemStorage(location=settings.MEDIA_ROOT)
USER_STATUSES = (
        ('A', 'Администратор'),
        ('S', 'Специалист'),
        ('O', 'Организация'),
    )
TYPE_PROOF = (
        ('STAMP1', 'Выявление печатей'),
        ('REC', 'Сверка реквизитов'),
        ('STAMP2', 'Печать без реквизитов'),
        ('STAMP3', 'Разные печати'),
        ('SIGN1', 'Выявленеи подписей'),
        ('SIGN2', 'Разные подписи'),
        ('1', 'ОС-1'),
        ('6', 'ОС-6'),
        ('NULL', 'Пустые страницы'),
        
    )
list_PROOF = {'item':['Выявление печатей','Сверка реквизитов', 'Печать без реквизитов','Разные печати','Выявленеи подписей','Разные подписи', 'ОС-1','ОС-6','Пустые страницы']}

class CreateUser(models.Model):
    ROLES = (
        ('A', 'Администратор'),
        ('S', 'Специалист'),
        ('O', 'Организация'),

    )

    name= models.CharField(max_length=100, null=True)
    last_name= models.CharField(max_length=100, null=True)
    roles = models.CharField(max_length=50, choices = ROLES, null=True)
    date_joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Роль'
        verbose_name_plural = 'Роли'

#Класс конкурса
class Conkurs(models.Model):
    name = models.CharField(max_length = 128, verbose_name='Название конкурса')
    logo = models.FileField('Изображение', storage=private_storage, default='settings.MEDIA_ROOT/anonymous.png')
    definition = models.CharField(max_length = 1000, verbose_name='Описание')
    #criteria = models.CharField(default=list_PROOF, max_length = 2000, verbose_name='Критерии проверки')
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Конкурс'
        verbose_name_plural = 'Конкурсы'

#Класс документа-образца
class DocExample(models.Model):
    name = models.CharField(max_length = 1000, verbose_name='Название документа')
    doc = models.FileField('Документ-образец', storage=private_storage, blank=True)
    mask = models.FileField('Документ-маска', storage=private_storage, blank=True)
    conkurs = models.ForeignKey(Conkurs, on_delete=models.CASCADE, null=True, verbose_name='Конкурс', related_name='conkurs')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Образец'
        verbose_name_plural = 'Образцы'

class Criteria(models.Model):
    name = models.CharField(max_length = 128, verbose_name='Критерий')
    criteria = models.ManyToManyField(Conkurs, blank=True, verbose_name='Конкурс', related_name='criteria')
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Критерий'
        verbose_name_plural = 'Критерии'
#Организации
class Org(models.Model):
    name = models.CharField(max_length = 500, verbose_name='Название')
    INN = models.CharField(max_length = 12, verbose_name='ИНН')
    conkurs = models.ManyToManyField(Conkurs, blank=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'
# Заявка
class Zayvka(models.Model):
    conkurs = models.ForeignKey(Conkurs, on_delete=models.CASCADE, null=True, verbose_name='Конкурс', related_name='zay')    
    org = models.ForeignKey(Org, on_delete=models.CASCADE, null=True, verbose_name='Организация', related_name='org')


    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Завки'
# Документы к заявке
class DocZayvka(models.Model):
    name = models.CharField(max_length = 1000, verbose_name='Название документа')
    doc = models.FileField('Документ', storage=private_storage, blank=True)
    mask = models.FileField('Маска', storage=private_storage, blank=True)
    zay = models.ForeignKey(Zayvka, on_delete=models.CASCADE, null=True, verbose_name='Заявка', related_name='zay')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Документ в заявке'
        verbose_name_plural = 'Документы в заявке'

proj/polls/forms.py
from django import forms
from .models import *
# from django.db import transaction
# from django.views.generic import UpdateView
# from leaflet.forms.widgets import LeafletWidget
# from leaflet.forms.fields import *
# #from django.contrib.gis import forms

class ConkursForm(forms.ModelForm):
    class Meta:
        model = Conkurs
        fields = "__all__"

# class PointSearchForm(forms.ModelForm):
    # class Meta:
        # model = SearchPoint
        # fields = ('name', 'loc')
        # geom = forms.PointField()
# class MyGeoForm(forms.Form):
    # point = forms.PointField(widget=
        # forms.OSMWidget(attrs={'map_width': 900, 'map_height': 500}))

proj/polls/views.py
# -*- coding: utf-8 -*-
from django.contrib.admin.models import LogEntry
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import plotly.offline as opy
import plotly.graph_objs as go
import datetime
from plotly.offline import plot
from plotly.graph_objs import *
import plotly.express as px
import numpy as np
import pandas as pd
import sys
import random
from .forms import *
from django.core.files.storage import FileSystemStorage
from django.http import QueryDict
from django.utils.datastructures import MultiValueDict

from absl import logging
import os
from pdf2image import convert_from_path
import json
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, ImageOps
from scipy.spatial import cKDTree
from skimage.feature import plot_matches
from skimage.measure import ransac
from skimage.transform import AffineTransform
from six import BytesIO
import tensorflow as tf
import tensorflow_hub as hub
from six.moves.urllib.request import urlopen
import cv2
import matplotlib.pyplot as plt
from skimage import measure, morphology
from skimage.color import label2rgb
from skimage.measure import regionprops
import filetype
from wand.image import Image
#from PIL import Image, ImageFont
import cv2 as cv
import matplotlib.pyplot as plt
from skimage import measure, morphology
from skimage.color import label2rgb
from skimage.measure import regionprops
import matplotlib.patches as mpatches
private_storage = FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT)
media_storage = FileSystemStorage(location=settings.MEDIA_ROOT)
delf = hub.load('model').signatures['default']
def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img = cv2.imread(os.path.join(folder,filename))
        if img is not None:
            images.append(img)
    return images
def download_and_resize(name,new_width=256, new_height=256):
  image = Image.open(name)
  image = ImageOps.fit(image, (new_width, new_height), Image.ANTIALIAS)
  image = image.convert('RGB')
  return image
def resize_image(name, destfile, new_width=256, new_height=256):
    pil_image = Image.open(name)
    pil_image = ImageOps.fit(pil_image, (new_width, new_height), Image.ANTIALIAS)
    pil_image_rgb = pil_image.convert('RGB')
    pil_image_rgb.save(destfile, format='JPEG', quality=90)
def run_delf(image):
  np_image = np.array(image)
  float_image = tf.image.convert_image_dtype(np_image, tf.float32)

  return delf(
      image=float_image,
      score_threshold=tf.constant(100.0),
      image_scales=tf.constant([0.25, 0.3536, 0.5, 0.7071, 1.0, 1.4142, 2.0]),
      max_feature_num=tf.constant(1000))
def filter_value( someList, value ):
    for x, y in someList:
        if x == value :
            yield x,y
def match_images(image1, image2):
  result1 = run_delf(image1)
  result2 = run_delf(image2)
  distance_threshold = 0.8

  # Read features.
  num_features_1 = result1['locations'].shape[0]
  print("Документ 1: %d признаков" % num_features_1)
  
  num_features_2 = result2['locations'].shape[0]
  print("Документ 2: %d признаков" % num_features_2)

  # Find nearest-neighbor matches using a KD tree.
  d1_tree = cKDTree(result1['descriptors'])
  _, indices = d1_tree.query(
      result2['descriptors'],
      distance_upper_bound=distance_threshold)

  # Select feature locations for putative matches.
  locations_2_to_use = np.array([
      result2['locations'][i,]
      for i in range(num_features_2)
      if indices[i] != num_features_1
  ])
  locations_1_to_use = np.array([
      result1['locations'][indices[i],]
      for i in range(num_features_2)
      if indices[i] != num_features_1
  ])

  # Perform geometric verification using RANSAC.
  _, inliers = ransac(
      (locations_1_to_use, locations_2_to_use),
      AffineTransform,
      min_samples=3,
      residual_threshold=20,
      max_trials=1000)

  print('Найдено %d схожих дескрипторов' % sum(inliers))
  return {"inliers": sum(inliers)}
class CVOutput:
    def __init__(self,image,error):
        self.image = image
        self.error = error
        
class SignatureItem:
    def __init__(self,minr,minc,maxr,maxc):
        self.minr = minr
        self.minc = minc
        self.maxr = maxr
        self.maxc = maxc
MIN_CONNECTED_THRESHOLD = 680
MAX_CONNECTED_THRESHOLD = 8000
DebugMode = True
def signature(INPUTIMAGE):
    image = cv2.imread(INPUTIMAGE,cv2.IMREAD_GRAYSCALE)


    # We NEED thresholding to remove vertical and horizontal lines
    thresh = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)[1]

    # Remove horizontal lines
    horizontal_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (40,1))
    remove_horizontal = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, horizontal_kernel, iterations=2)
    cnts = cv2.findContours(remove_horizontal, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]
    for c in cnts:
        cv2.drawContours(image, [c], -1, (255,255,255), 5)
         
    # Remove vertical lines
    vertical_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (1,40))
    remove_vertical = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, vertical_kernel, iterations=2)
    cnts = cv2.findContours(remove_vertical, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]
    for c in cnts:
        cv2.drawContours(image, [c], -1, (255,255,255), 5)


    ObjOut = CVOutput(image,None)
    img = ObjOut.image

    # Uncomment the following line to create an image without lines       
    #cv2.imwrite("./inputs/out5.png",ObjOut.image)

    #img = image
    # connected component analysis by scikit-learn framework
    blobs = img > img.mean()
    blobs_labels = measure.label(blobs, background=1)
    image_label_overlay = label2rgb(blobs_labels, image=img)

    fig, ax = plt.subplots(figsize=(10, 6))

    the_biggest_component = 0

    AllSignatures = []

    for region in regionprops(blobs_labels):

        if (region.area >= MIN_CONNECTED_THRESHOLD and region.area < MAX_CONNECTED_THRESHOLD):
            if (region.area > the_biggest_component):
                the_biggest_component = region.area
                
            minr, minc, maxr, maxc = region.bbox
            signature = SignatureItem(minr, minc, maxr, maxc)
            #print("debug:"+str(minr))
            rect = mpatches.Rectangle((minc, minr), maxc - minc, maxr - minr,fill=False, edgecolor='red', linewidth=2)
            ax.add_patch(rect)
            AllSignatures.append(signature)
        
    print("Найдено рукописных подписей:" + str(len(AllSignatures)))
    return len(AllSignatures)

#Главная страница
@login_required
def index(request):
    conkurs = Conkurs.objects.all()
    docs = DocExample.objects.all()
    orgs = Org.objects.all()
    zayas = Zayvka.objects.all()
    content = {'conkurs':conkurs, 'docs':docs, 'orgs':orgs, 'zayas':zayas}
    return render(request, 'polls/index.html', content)
    
    
#Новый конкурс
@login_required
def new_conkurs(request):
    conkurs = Conkurs.objects.all()
    if request.POST:
            
        new_conkurs = Conkurs(
                name=request.POST['name'], definition=request.POST['definition'], logo=request.FILES['logo']
                )
        
        new_conkurs.save()
        for i  in request.FILES.getlist('files[]'):
            new_doc = DocExample (
                        name=str(i), doc=i, conkurs = new_conkurs
                        )
            new_doc.save()
        return HttpResponseRedirect('/')
    content = {'conkurs':conkurs}
    return render(request, 'polls/create/new_conkurs.html', content)

#Просмотр конкурса
@login_required
def conkurs(request, conkurs_id):
    conkurs = Conkurs.objects.all()
    real_conkurs = Conkurs.objects.get(id=conkurs_id)
    docs = DocExample.objects.filter(conkurs=real_conkurs)
    print(request.user)
    content = {'conkurs':conkurs, 'real_conkurs':real_conkurs, 'docs':docs, 'TYPE_PROOF':TYPE_PROOF, 'user':request.user}
    return render(request, 'polls/conkurs.html', content)

#Настройка проверки конкурса
@login_required
def edit_conkurs(request, conkurs_id):
    conkurs = Conkurs.objects.all()
    real_conkurs = Conkurs.objects.get(id=conkurs_id)
    docs = DocExample.objects.filter(conkurs=real_conkurs)
    if request.POST:
        
        new_conkurs = Conkurs(
                    name=real_conkurs.name, definition=request.POST['definition'], logo=real_conkurs.logo
                    )
        new_conkurs.save()
        for i  in request.FILES.getlist('files[]'):
            new_doc = DocExample (
                        name=str(i), doc=i, conkurs = new_conkurs
                        )
            new_doc.save()
        for i  in request.POST.getlist('docs'):
            new_doc = DocExample (
                        name=str(i), doc=i, conkurs = new_conkurs
                        )
            new_doc.save()
        # for i in request.POST.getlist('criteria'):
            # new_criteria = Criteria(name=str(i), criteria=new_conkurs)
        docs.delete()
        real_conkurs.delete()
        return HttpResponseRedirect('/conkurs/'+str(new_conkurs.id))
    content = {'conkurs':conkurs, 'real_conkurs':real_conkurs, 'docs':docs, 'TYPE_PROOF':TYPE_PROOF, 'user':request.user}
    return render(request, 'polls/edit_conkurs.html', content)    
#Просмотр документа
@login_required
def doc(request, doc_id):
    conkurs = Conkurs.objects.all()
    doc = DocExample.objects.get(id=doc_id)
    content = {'conkurs':conkurs, 'doc':doc}
    return render(request, 'polls/doc.html', content)
@login_required
def doc_z(request, doc_id):
    conkurs = Conkurs.objects.all()

proj/polls/templates/polls/index.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Главная страница{% endblock %}
{% block css %}
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static '/polls/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static '/polls/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
{% endblock %}

{% block content %}
    {% block page %}
<div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Статистика применения "КОМПЛЕКТА"</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
		<!-- Info boxes -->
        <div class="row">
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box">
              <span class="info-box-icon bg-info elevation-1"><i class="fas fa-globe"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Закупки</span>
                <span class="info-box-number">
                  {{ conkurs|length }}
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-info elevation-1"><i class="fab fa-superpowers"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Заявки</span>
                <span class="info-box-number">{{ zayas|length }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>

          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-info elevation-1"><i class="fas fa-atom"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Организации</span>
                <span class="info-box-number">{{ orgs|length }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-info elevation-1"><i class="far fa-file-alt"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Документы</span>
                <span class="info-box-number">{{ docs|length }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
		<div class="raw">
		<div class="col-12">
		<div class="card">
		 <div class="card-header">
                <h3 class="card-title">
                 Закупки
                </h3>

                <div class="card-tools">
				<button type="button" class="btn btn-info" data-card-widget="collapse" data-toggle="tooltip" title="Развернуть"><i class="fas fa-expand"></i>
                  </button>
				 <a href="{% url 'polls:new_conkurs' %}" type="button" class="btn btn-info float-right"data-toggle="tooltip" title="Добавить объект"><i class="fas fa-plus"></i></a>
                </div>
              </div>
            <!-- /.card-header -->
			<div class="card-body p-0">
			{% if conkurs|length == 0 %}					
			<div>Нет данных о конкурсах</div>
			<br>
			{% else %} 
                    <ul class="users-list clearfix">
					{% for i in conkurs %}
                      <li>
                        <a href="{% url 'polls:conkurs' i.id%}"><img src="/static/files/{{i.logo}}" alt="User Image"></a>
                        <a class="users-list-name" href="{% url 'polls:conkurs' i.id%}">{{i.name}}</a>
                        <a href="{% url 'polls:conkurs' i.id%}"><span class="users-list-date">Основной конкурс</span></a>
                      </li>
					  {% endfor %}
                    </ul>
			{% endif %}
                    <!-- /.users-list -->
                  </div>
                  
           
          </div>
          <!-- /.card -->
		
		</div>
          <!-- /.col -->
		</div>
        <!-- /.row -->
		<div class="raw">
		<div class="col-12">
		<div class="card">
		 <div class="card-header">
                <h3 class="card-title">
                 Заявки
                </h3>

                <div class="card-tools">
				<button type="button" class="btn btn-info" data-card-widget="collapse" data-toggle="tooltip" title="Развернуть"><i class="fas fa-expand"></i>
                  </button>
				<a href="{% url 'polls:new_zay' %}" type="button" class="btn btn-info float-right"data-toggle="tooltip" title="Добавить объект"><i class="fas fa-plus"></i></a>
                </div>
              </div>
            <!-- /.card-header -->
            <div class="card-body">
			{% if zayas|length == 0 %}					
			<div>Нет данных о заявках</div>
			<br>
			{% else %} 
              <table id="example2" class="table table-bordered table-striped">
                <thead align="center">
                <tr>
                  <th>Конкурс</th>
                  <th>Организация</th>
                  <th>Документов <br>отправлено</th>
				  <th>Типы документов</th>
                  <th>Ошибки</th>
				  <th>Действия</th>
                </tr>
                </thead>
                <tbody align="center">
				{% for i in zayas %}
                <tr>
                  <td>{{i.conkurs.name}}</td>
                  <td>{{i.org.name}}</td>
				  <td>{{i.zay.all|length}}</td>
                  <td>{% for d in i.zay.all %} <a href="{% url 'polls:doc_z' d.id%}">{{d.name}}</a><br>{% endfor %}</td>
                  <td>{{sys.sat.all|length}}</td>
				 <td align="center">
				  <div class="btn-group">
                        <a href="{% url 'polls:results' i.id%}"type="button" class="btn btn-info" data-toggle="tooltip" title="Просмотреть"><i class="fab fa-hornbill"></i></a>
                      </div>
				  </td>
                </tr>
				{% endfor %}
                </tbody>
              </table>
			  {% endif %}
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
		
		</div>
          <!-- /.col -->
		</div>
        <!-- /.row -->
		<div class="raw">
		<div class="col-12">
		<div class="card">
		 <div class="card-header">
                <h3 class="card-title">
                 Организации
                </h3>
                <div class="card-tools">
				<button type="button" class="btn btn-info" data-card-widget="collapse" data-toggle="tooltip" title="Развернуть"><i class="fas fa-expand"></i>
                  </button>
				 <a href="{% url 'polls:new_org' %}" type="button" class="btn btn-info float-right"data-toggle="tooltip" title="Добавить объект"><i class="fas fa-plus"></i></a>
                </div>
				 </div>
            <!-- /.card-header -->
            <div class="card-body">
			{% if orgs|length == 0 %}					
			<div>Нет данных об организациях</div>
			<br>
			{% else %} 
              <table id="example1" class="table table-bordered table-striped">
                <thead align="center">
                <tr>
					<th>Организация</th>
					<th>ИНН</th>
					<th>Конкурсы</th>
                    <th>Документы</th>
                    <th>Верификация</th>
					<th>Рейтинг</th>
                </tr>
                </thead>
                <tbody align="center">
				{% for i in orgs %}
                <tr>
				<td>{{i.name}}</td>
				<td>{{i.INN}}</td>
                  <td>{% for j in i.conkurs.all %}
				  {{ j.name }}
				  {% endfor %}</td>
                  <td></td>
                  <td></td>
				  <th>
                </tr>
				{% endfor %}
                </tbody>
              </table>
			  {% endif %}
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
		</div>
          <!-- /.col -->
		</div>
        <!-- /.row -->
	
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    {% endblock page %}
{% endblock content %}
{% block scripts %}
<!-- DataTables -->
<script src="{% static '/polls/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static '/polls/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static '/polls/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static '/polls/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/polls/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
	$("#example2").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
		$("#example3").DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
	$("#example4").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
  });
</script>
{% endblock %}